name: OnlyKola
favicon: null
layout_spectrum: 0.4693540788721293
typography_spectrum: 0.5938063182402402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5610837750136852
  lightness: 0.7974540565628558
  saturation: 0.7697993151377887
  rhythmicContrast: 0.6068855915218592
purpose: []
