analytics: {}
color:
  brandColors:
    - '#E0F0F0'
    - '#642121'
    - '#808890'
    - '#C85858'
    - '#F8D0A0'
  brandStrength: 0.561083
  lightness: 0.797454
  rhythmicContrast: 0.804898
  saturation: 0.769799
cta: {}
layout_spectrum: 0.886824
name: OnlyKola
opengraph: {}
purpose: []
typography_spectrum: 0.122466
